version: '3'

services:
  frontend:
    container_name: mospan_pro_frontend
    restart: always
    build: .
    networks:
      mospan:
    ports:
      - '80:80'

networks:
  mospan:
    external: true
